"""empty message

Revision ID: 32a2def3b69a
Revises: 
Create Date: 2025-01-03 15:39:03.980142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a2def3b69a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.drop_column('isComplete')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guide', sa.Boolean(), nullable=True))
        batch_op.drop_column('isGuide')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isGuide', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_guide')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isComplete', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
