"""added ondelete to fks

Revision ID: bb34d5dc21b1
Revises: 1b265a94060f
Create Date: 2025-01-24 15:19:17.514558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb34d5dc21b1'
down_revision = '1b265a94060f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('fk_availability_tour', type_='foreignkey')
        batch_op.drop_constraint('fk_availability_guide', type_='foreignkey')
        batch_op.create_foreign_key('fk_availability_tour', 'preset_tours', ['tour_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_availability_guide', 'guides', ['guide_id'], ['nid'], ondelete='CASCADE')

    with op.batch_alter_table('preset_tours', schema=None) as batch_op:
        batch_op.drop_constraint('preset_tours_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tours', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_guide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'guides', ['guide_id'], ['nid'], ondelete='CASCADE')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_constraint('tours_guide_nid_fkey', type_='foreignkey')
        batch_op.drop_constraint('tours_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'guides', ['guide_nid'], ['nid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tours_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('tours_guide_nid_fkey', 'guides', ['guide_nid'], ['nid'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_guide_id_fkey', 'guides', ['guide_id'], ['nid'])
        batch_op.create_foreign_key('reviews_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('preset_tours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('preset_tours_id_fkey', 'tours', ['id'], ['id'])

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('fk_availability_guide', type_='foreignkey')
        batch_op.drop_constraint('fk_availability_tour', type_='foreignkey')
        batch_op.create_foreign_key('fk_availability_guide', 'guides', ['guide_id'], ['nid'])
        batch_op.create_foreign_key('fk_availability_tour', 'preset_tours', ['tour_id'], ['id'])

    # ### end Alembic commands ###
