"""empty message

Revision ID: fb1eae3c5acf
Revises: a2d15e02e89f
Create Date: 2025-01-24 15:13:23.747668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1eae3c5acf'
down_revision = 'a2d15e02e89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.alter_column('nid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_constraint('guides_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('guides_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('nid',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
